A.1 Matrix Multiplication (Resource Allocation)

In [1]:
import numpy as np

Resources_Matrix = np.array([
    [10, 20],
    [30, 40],
    [50, 60]
])  # 3×2

Allocation_Factors = np.array([
    [0.5, 1.0],
    [1.5, 2.0]
])  # 2×2

Result = Resources_Matrix @ Allocation_Factors
print("Resource Distribution:\n", Result)

Resource Distribution:
 [[ 35.  50.]
 [ 75. 110.]
 [115. 170.]]


A.2 Element-wise Operations

In [2]:
Shift_A_Production = np.array([10, 12, 11, 13, 15, 14, 16])
Shift_B_Production = np.array([9, 11, 10, 12, 14, 13, 15])

Total_Production = Shift_A_Production + Shift_B_Production
print("Total Production:", Total_Production)

Total Production: [19 23 21 25 29 27 31]


A.3 Sigmoid Function

In [3]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

test_values = np.array([-2, -1, 0, 1, 2])
print("Sigmoid:", sigmoid(test_values))

Sigmoid: [0.11920292 0.26894142 0.5        0.73105858 0.88079708]


A.4 Sigmoid Gradient

In [4]:
def sigmoid_grad(x):
    s = sigmoid(x)
    return s * (1 - s)

print("Sigmoid Gradient:", sigmoid_grad(test_values))

Sigmoid Gradient: [0.10499359 0.19661193 0.25       0.19661193 0.10499359]


C. NumPy 💻

In [5]:
import numpy as np

# Dataset
X = np.array([
    [20, 3, 4],
    [15, 5, 3],
    [30, 2, 2],
    [25, 4, 1],
    [35, 2, 3]
]).T  # shape (3,5)

Y = np.array([[18, 20, 22, 25, 30]])

# Initialize
np.random.seed(1)
W1 = np.random.randn(3,3) * 0.01
b1 = np.zeros((3,1))
W2 = np.random.randn(1,3) * 0.01
b2 = np.zeros((1,1))

lr = 0.0001
m = X.shape[1]

def relu(x): return np.maximum(0, x)
def relu_grad(x): return x > 0
def sigmoid(x): return 1/(1+np.exp(-x))

losses = []

for i in range(5000):
    # Forward
    Z1 = W1 @ X + b1
    A1 = relu(Z1)
    Z2 = W2 @ A1 + b2
    A2 = sigmoid(Z2)

    loss = np.mean((A2 - Y)**2)
    losses.append(loss)

    # Backward
    dA2 = 2*(A2 - Y)/m
    dZ2 = dA2 * A2*(1-A2)
    dW2 = dZ2 @ A1.T
    db2 = np.sum(dZ2, axis=1, keepdims=True)

    dA1 = W2.T @ dZ2
    dZ1 = dA1 * relu_grad(Z1)
    dW1 = dZ1 @ X.T
    db1 = np.sum(dZ1, axis=1, keepdims=True)

    # Update
    W2 -= lr*dW2
    b2 -= lr*db2
    W1 -= lr*dW1
    b1 -= lr*db1

print("W1:\n", W1)
print("b1:\n", b1)
print("W2:\n", W2)
print("b2:\n", b2)

# Predictions
Z1 = W1 @ X + b1
A1 = relu(Z1)
Z2 = W2 @ A1 + b2
A2 = sigmoid(Z2)

print("Predictions:\n", A2)

W1:
 [[ 6.28559568e-01  1.09121651e-01  7.70752671e-02]
 [-1.07296862e-02  8.65407629e-03 -2.30153870e-02]
 [ 4.09226058e-04 -9.56378067e-03  1.55950181e-03]]
b1:
 [[ 0.02947167]
 [ 0.        ]
 [-0.0006431 ]]
W2:
 [[ 0.64304017  0.01462108 -0.01189509]]
b2:
 [[0.19074402]]
Predictions:
 [[0.99983381 0.99885599 0.99999654 0.99997617 0.99999956]]
